services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: wordpress:user
    build: requirements/wordpress/
    container_name: wp-php
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    env_file:
      .env
    depends_on: 
      - mariadb
    restart: always

  mariadb:
    image: mariadb:user
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      .env
    restart: always

volumes:
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/avialle-/data/mariadb
      o: bind
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/avialle-/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge