services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress/
    container_name: wp-php
    ports:
      - "9000:9000"
    volumes:
      - ./requirements/wordpress/conf:/var/www/html
    networks:
      - inception_network
    env_file:
      .env

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/avialle-/Documents/Inception/srcs/requirements/mariadb/conf:/var/lib/mysql:rw
    networks:
      - inception_network
    env_file:
      .env

networks:
  inception_network:
    driver: bridge