version: "3.8"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "8080:80"
  # wordpress:
  #   build: requirements/wordpress/
  #   container_name: wp-php
  # mariadb:
  #   build: requirements/mariadb/
  #   container_name: mariadb