version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: wordpress
    build: requirements/wordpress/
    container_name: wp-php
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      .env
    depends_on: mariadb
    restart: always

  mariadb:
    image: mariadb
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      .env
    restart: always

volumes:
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/mariadb/data
      o: bind
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/wordpress/data
      o: bind

networks:
  inception_network:
    driver: bridge